### ISSUE TITLE
Refactor patch_db.txt as patch_000x.txt

### ISSUE THREAD

**Issue by ProgrammerDan** [DevotedMC/Devotion#4]
E.g. after several patches they would be:

patch_0001.txt
patch_0002.txt
patch_0003.txt

Add a management table as well to keep track of last patch level applied, and start seeking patches at above that patch level.

**Comment by Aleksey-Terzi** [comment]
Improvements is implemented.
Management table named as dev_patch.

**Comment by ProgrammerDan** [comment]
Thank you! Can you actually go ahead and have patch_0001 be the fishing patch? Then have the block break be patch_0002? Thanks.

**Comment by Aleksey-Terzi** [comment]
Done.
